remote_theme: just-the-docs/just-the-docs
title: Encoded Archival Standards Best Practices Guide
author: Society of American Archivists Technical Subcommittee on Encoded Archival Standards (SAA TS-EAS)

repository: SAA-SDT/EAS-Best-Practices # for github-metadata

logo: "/images/SAAHoriz-Blue_200.png"

color_scheme: blue

aux_links:
  "EAS BPG on GitHub":
    - "https://github.com/SAA-SDT/EAS-Best-Practices/"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
